<a href="https://colab.research.google.com/github/just-joseph/Python-basics/blob/master/Copy_of_Python_day4_numpy%2C_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create a python numpy array by passing a list or tuple
a = np.array([1, 2, 3])   # you can also use ((1,2,3))
type(a)

numpy.ndarray

In [ ]:
# Passing a list of list creates a 2D or n-D array
a = np.array( [[1, 2, 3],[4,5,6],[7,8,9]] )   
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.ones( (3,4), dtype= np.int8 )

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [ ]:
np.full( (3,4), 5 )

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
# Create array with range from 10 to 30 (30 excluded), incrementing by 5
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [ ]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
# In arange, we specify the increment. In linspace, we specify the number of split we need between the start and end value
# Here, 0 to 5 is split into 10
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
a = np.array( [[1, 2, 3],[4,5,6],[7,8,9],[10,11,12]] )
a.reshape(6,2)  

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

### Data analysis

In [ ]:
# Pandas dataframe creation using a dictionary. The keys in dictionary can be column names, and values of dictionary are the columns of dataframe
data = pd.DataFrame({'Country': ['Russia','Colombia','Chile','Equador','Nigeria'],
                     'Rank':[121,40,100,130,11]})

In [ ]:
# Produces top rows of the dataframe. We also have tail() to produce bottom rows.
data.head()

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [ ]:
# A basic methematical description of all columns
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [ ]:
# Information on the dataframe and all the columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [ ]:
data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

# take note of the inplace keyword as it is used in multiple functions
data.sort_values(by=['ounces'],ascending=True,inplace=False)

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [ ]:
# Sorting by 2 columns
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)

group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

In [ ]:
data.drop_duplicates()
# data.drop_dulicates( subset=['group'])   #use this to drop duplicate rows based on certain columns

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [ ]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [ ]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

def meat_2_animal(series):
    if series['food'] == 'bacon':
        return 'pig'
    elif series['food'] == 'pulled pork':
        return 'pig'
    elif series['food'] == 'pastrami':
        return 'cow'
    elif series['food'] == 'corned beef':
        return 'cow'
    elif series['food'] == 'honey ham':
        return 'pig'
    else:
        return 'salmon'


#create a new variable
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [ ]:
#another way of doing it is: convert the food values to the lower case and apply the function
lower = lambda x: x.lower()
data['food'] = data['food'].apply(lower)
data['animal2'] = data.apply(meat_2_animal, axis='columns')
data

food  ounces  animal animal2
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

In [ ]:
data.assign(new_variable = data['ounces']*10)

food  ounces  animal animal2  new_variable
0        bacon     4.0     pig     pig          40.0
1  pulled pork     3.0     pig     pig          30.0
2        bacon    12.0     pig     pig         120.0
3     pastrami     6.0     cow     cow          60.0
4  corned beef     7.5     cow     cow          75.0
5        bacon     8.0     pig     pig          80.0
6     pastrami     3.0     cow     cow          30.0
7    honey ham     5.0     pig     pig          50.0
8     nova lox     6.0  salmon  salmon          60.0

In [ ]:
data.drop('animal2',axis='columns',inplace=True)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [ ]:
# returns a dataframe with a single column
data[['food']]

# data['food'] returns a single column (i.e. pandas series, not a single column dataframe)

food
0        bacon
1  pulled pork
2        bacon
3     pastrami
4  corned beef
5        bacon
6     pastrami
7    honey ham
8     nova lox

In [ ]:
df= pd.read_csv('http://46.101.230.157/dilan/pandas_tutorial_read.csv', delimiter=';')
df.head()

2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
0  2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
1  2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
2  2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
3  2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America
4  2018-01-01 00:05:42  read  country_6  2458151266   Reddit  North America

In [ ]:
column_names= ['my_datetime', 'event', 'country', 'user_id', 'source', 'topic']
df= pd.read_csv('http://46.101.230.157/dilan/pandas_tutorial_read.csv', delimiter=';', names= column_names)

In [ ]:
df.head()

my_datetime event    country     user_id   source          topic
0  2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1  2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2  2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3  2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4  2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America

In [ ]:
# Selecting rows based on conditions
df [ df['source'] == 'SEO']

my_datetime event    country     user_id source          topic
0     2018-01-01 00:01:01  read  country_7  2458151261    SEO  North America
1     2018-01-01 00:03:20  read  country_7  2458151262    SEO  South America
11    2018-01-01 00:08:57  read  country_7  2458151272    SEO      Australia
15    2018-01-01 00:11:22  read  country_7  2458151276    SEO  North America
16    2018-01-01 00:13:05  read  country_8  2458151277    SEO  North America
...                   ...   ...        ...         ...    ...            ...
1772  2018-01-01 23:45:58  read  country_7  2458153033    SEO  South America
1777  2018-01-01 23:49:52  read  country_5  2458153038    SEO  North America
1779  2018-01-01 23:51:25  read  country_4  2458153040    SEO  South America
1784  2018-01-01 23:54:03  read  country_2  2458153045    SEO  North America
1791  2018-01-01 23:58:33  read  country_8  2458153052    SEO           Asia

[346 rows x 6 columns]

In [ ]:
# Selecting rows based on condition, and choosing only selected columns from that
df[ df.source == 'SEO'][['user_id','topic', 'country']]

user_id          topic    country
0     2458151261  North America  country_7
1     2458151262  South America  country_7
11    2458151272      Australia  country_7
15    2458151276  North America  country_7
16    2458151277  North America  country_8
...          ...            ...        ...
1772  2458153033  South America  country_7
1777  2458153038  North America  country_5
1779  2458153040  South America  country_4
1784  2458153045  North America  country_2
1791  2458153052           Asia  country_8

[346 rows x 3 columns]

## Grouping

In [ ]:
zoo= pd.read_csv('http://46.101.230.157/datacoding101/zoo.csv', delimiter = ',')

In [ ]:
zoo.head()

animal  uniq_id  water_need
0  elephant     1001         500
1  elephant     1002         600
2  elephant     1003         550
3     tiger     1004         300
4     tiger     1005         320

In [ ]:
zoo.shape

(22, 3)

In [ ]:
print(zoo['animal'].count())
print( zoo['animal'].unique() )
print( len( zoo['animal'].unique() ))

22
['elephant' 'tiger' 'zebra' 'lion' 'kangaroo']
5


In [ ]:
print(zoo.water_need.sum())
print(zoo.water_need.min())
print(zoo.water_need.max())
print(zoo.water_need.mean())
print(zoo.water_need.median())

7650
80
600
347.72727272727275
325.0


In [ ]:
zoo.groupby('animal').mean()

uniq_id  water_need
animal                       
elephant   1002.0  550.000000
kangaroo   1021.0  416.666667
lion       1017.5  477.500000
tiger      1006.0  310.000000
zebra      1012.0  184.285714

In [ ]:
zoo.groupby('animal').mean()[['water_need']]
# zoo.groupby('animal').mean()['water_need'] will return a series instead of dataframe

water_need
animal              
elephant  550.000000
kangaroo  416.666667
lion      477.500000
tiger     310.000000
zebra     184.285714

In [ ]:
zoo['animal'].value_counts()

zebra       7
tiger       5
lion        4
kangaroo    3
elephant    3
Name: animal, dtype: int64

### Merge

In [ ]:
zoo_eats = pd.DataFrame(
           [['elephant','vegetables'], ['tiger','meat'], ['kangaroo','vegetables'], ['zebra','vegetables'], ['giraffe','vegetables']], 
           columns=['animal', 'food']
                       )

In [ ]:
print(zoo.animal.unique())
print(zoo_eats.animal.unique())

['elephant' 'tiger' 'zebra' 'lion' 'kangaroo']
['elephant' 'tiger' 'kangaroo' 'zebra' 'giraffe']


In [ ]:
zoo.merge(zoo_eats)
# On analysis, we understand that we lost the rows with 'animal = lion' as we did not map for that 
# This is because default is inner merge

animal  uniq_id  water_need        food
0   elephant     1001         500  vegetables
1   elephant     1002         600  vegetables
2   elephant     1003         550  vegetables
3      tiger     1004         300        meat
4      tiger     1005         320        meat
5      tiger     1006         330        meat
6      tiger     1007         290        meat
7      tiger     1008         310        meat
8      zebra     1009         200  vegetables
9      zebra     1010         220  vegetables
10     zebra     1011         240  vegetables
11     zebra     1012         230  vegetables
12     zebra     1013         220  vegetables
13     zebra     1014         100  vegetables
14     zebra     1015          80  vegetables
15  kangaroo     1020         410  vegetables
16  kangaroo     1021         430  vegetables
17  kangaroo     1022         410  vegetables

In [ ]:
zoo.merge(zoo_eats, how = 'outer')

animal  uniq_id  water_need        food
0   elephant   1001.0       500.0  vegetables
1   elephant   1002.0       600.0  vegetables
2   elephant   1003.0       550.0  vegetables
3      tiger   1004.0       300.0        meat
4      tiger   1005.0       320.0        meat
5      tiger   1006.0       330.0        meat
6      tiger   1007.0       290.0        meat
7      tiger   1008.0       310.0        meat
8      zebra   1009.0       200.0  vegetables
9      zebra   1010.0       220.0  vegetables
10     zebra   1011.0       240.0  vegetables
11     zebra   1012.0       230.0  vegetables
12     zebra   1013.0       220.0  vegetables
13     zebra   1014.0       100.0  vegetables
14     zebra   1015.0        80.0  vegetables
15      lion   1016.0       420.0         NaN
16      lion   1017.0       600.0         NaN
17      lion   1018.0       500.0         NaN
18      lion   1019.0       390.0         NaN
19  kangaroo   1020.0       410.0  vegetables
20  kangaroo   1021.0       430.0  vegetables
21  kangaroo   1022.0       410.0  vegetables
22   giraffe      NaN         NaN  vegetables

In [ ]:
zoo.merge(zoo_eats, how = 'left')

animal  uniq_id  water_need        food
0   elephant     1001         500  vegetables
1   elephant     1002         600  vegetables
2   elephant     1003         550  vegetables
3      tiger     1004         300        meat
4      tiger     1005         320        meat
5      tiger     1006         330        meat
6      tiger     1007         290        meat
7      tiger     1008         310        meat
8      zebra     1009         200  vegetables
9      zebra     1010         220  vegetables
10     zebra     1011         240  vegetables
11     zebra     1012         230  vegetables
12     zebra     1013         220  vegetables
13     zebra     1014         100  vegetables
14     zebra     1015          80  vegetables
15      lion     1016         420         NaN
16      lion     1017         600         NaN
17      lion     1018         500         NaN
18      lion     1019         390         NaN
19  kangaroo     1020         410  vegetables
20  kangaroo     1021         430  vegetables
21  kangaroo     1022         410  vegetables

In [ ]:
# It is a good practice to specify the columns on which we want to merge
# In previous case, the only common column for zoo and zoo_eats was 'animal', hence there were no confusions.
zoo.merge(zoo_eats, how = 'left', left_on = 'animal', right_on = 'animal')

animal  uniq_id  water_need        food
0   elephant     1001         500  vegetables
1   elephant     1002         600  vegetables
2   elephant     1003         550  vegetables
3      tiger     1004         300        meat
4      tiger     1005         320        meat
5      tiger     1006         330        meat
6      tiger     1007         290        meat
7      tiger     1008         310        meat
8      zebra     1009         200  vegetables
9      zebra     1010         220  vegetables
10     zebra     1011         240  vegetables
11     zebra     1012         230  vegetables
12     zebra     1013         220  vegetables
13     zebra     1014         100  vegetables
14     zebra     1015          80  vegetables
15      lion     1016         420         NaN
16      lion     1017         600         NaN
17      lion     1018         500         NaN
18      lion     1019         390         NaN
19  kangaroo     1020         410  vegetables
20  kangaroo     1021         430  vegetables
21  kangaroo     1022         410  vegetables

In [ ]:
zoo.sort_values(by = ['water_need'], ascending = False).head()

animal  uniq_id  water_need
1   elephant     1002         600
16      lion     1017         600
2   elephant     1003         550
0   elephant     1001         500
17      lion     1018         500

In [ ]:
zoo.sort_values(by = ['water_need'], ascending = False).reset_index().head()

index    animal  uniq_id  water_need
0      1  elephant     1002         600
1     16      lion     1017         600
2      2  elephant     1003         550
3      0  elephant     1001         500
4     17      lion     1018         500

In [ ]:
zoo.sort_values(by = ['water_need'], ascending = False).reset_index(drop = True).head()

animal  uniq_id  water_need
0  elephant     1002         600
1      lion     1017         600
2  elephant     1003         550
3  elephant     1001         500
4      lion     1018         500

In [ ]:
zoo.merge(zoo_eats, how = 'left').fillna('unknown')

animal  uniq_id  water_need        food
0   elephant     1001         500  vegetables
1   elephant     1002         600  vegetables
2   elephant     1003         550  vegetables
3      tiger     1004         300        meat
4      tiger     1005         320        meat
5      tiger     1006         330        meat
6      tiger     1007         290        meat
7      tiger     1008         310        meat
8      zebra     1009         200  vegetables
9      zebra     1010         220  vegetables
10     zebra     1011         240  vegetables
11     zebra     1012         230  vegetables
12     zebra     1013         220  vegetables
13     zebra     1014         100  vegetables
14     zebra     1015          80  vegetables
15      lion     1016         420     unknown
16      lion     1017         600     unknown
17      lion     1018         500     unknown
18      lion     1019         390     unknown
19  kangaroo     1020         410  vegetables
20  kangaroo     1021         430  vegetables
21  kangaroo     1022         410  vegetables

Apply, map, applymap, lambda

In [ ]:
np.random.randn(4,3)

array([[ 1.33861033,  0.01972253, -1.9324235 ],
       [-0.7204311 ,  1.40740796, -1.02297716],
       [ 0.44087879,  0.74389361,  0.04644209],
       [ 1.09316869, -1.13513327, -1.31229652]])

In [ ]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.182623 -0.920761 -0.914476
Ohio   -0.690036  1.436254  1.192276
Texas  -0.987276 -0.865107  2.245722
Oregon -2.195770 -0.957836  1.377365

In [ ]:
# Applying a function on 1D arrays to each column or row. DataFrame’s apply method does exactly this:

f = lambda x: x.max() - x.min()

# column wise (by default, axis=0)
frame.apply(f)

b    2.378393
d    2.394090
e    3.160198
dtype: float64

In [ ]:
frame.apply(f, axis=1)

Utah      1.103384
Ohio      2.126289
Texas     3.232998
Oregon    3.573135
dtype: float64

In [ ]:
frame

b         d         e
Utah    0.182623 -0.920761 -0.914476
Ohio   -0.690036  1.436254  1.192276
Texas  -0.987276 -0.865107  2.245722
Oregon -2.195770 -0.957836  1.377365

In [ ]:
# Applymap is used to perform an operation on all cells
frame.applymap(lambda x: x+1)

b         d         e
Utah    1.182623  0.079239  0.085524
Ohio    0.309964  2.436254  2.192276
Texas   0.012724  0.134893  3.245722
Oregon -1.195770  0.042164  2.377365

In [ ]:
# If for one series, we can use map function. i.e. Map function when extended to a whole dataframe is the applymap function
frame['e'].map(lambda x: '%.2f' % x)

Utah      -0.91
Ohio       1.19
Texas      2.25
Oregon     1.38
Name: e, dtype: object

DataFrame.apply operates on entire rows or columns at a time.
DataFrame.applymap, Series.apply, and Series.map operate on one element at time.
https://stackoverflow.com/questions/19798153/difference-between-map-applymap-and-apply-methods-in-pandas

Selection in dataframe- by label

In [ ]:
frame

b         d         e
Utah    0.182623 -0.920761 -0.914476
Ohio   -0.690036  1.436254  1.192276
Texas  -0.987276 -0.865107  2.245722
Oregon -2.195770 -0.957836  1.377365

In [ ]:
# We already saw frame['b'], frame[['b']] etc.

frame.loc[ :, ['b','d']]

b         d
Utah    0.182623 -0.920761
Ohio   -0.690036  1.436254
Texas  -0.987276 -0.865107
Oregon -2.195770 -0.957836

In [ ]:
frame.loc[ 0:2, ['b','d'] ]

TypeError: ignored

In [ ]:
frame.reset_index(inplace=True)
frame

index         b         d         e
0    Utah  0.182623 -0.920761 -0.914476
1    Ohio -0.690036  1.436254  1.192276
2   Texas -0.987276 -0.865107  2.245722
3  Oregon -2.195770 -0.957836  1.377365

In [ ]:
# We were able to use 0:2 in loc only because the index were in numbers. Else we need to use iloc to index dataframe by position

frame.loc[ 0:2, ['b','d'] ]

b         d
0  0.182623 -0.920761
1 -0.690036  1.436254
2 -0.987276 -0.865107

Selection by position

In [ ]:
frame

index         b         d         e
0    Utah  0.182623 -0.920761 -0.914476
1    Ohio -0.690036  1.436254  1.192276
2   Texas -0.987276 -0.865107  2.245722
3  Oregon -2.195770 -0.957836  1.377365

In [ ]:
frame.iloc[3]

index      Oregon
b        -2.19577
d       -0.957836
e         1.37736
Name: 3, dtype: object

In [ ]:
frame.iloc[[1, 2, 3], [1, 2]]

b         d
1 -0.690036  1.436254
2 -0.987276 -0.865107
3 -2.195770 -0.957836

In [ ]:
frame.iloc[1:4, 1:3]

b         d
1 -0.690036  1.436254
2 -0.987276 -0.865107
3 -2.195770 -0.957836

In [ ]:
frame.iloc[1, 1]

-0.6900358241137957

Other operations

In [ ]:
df = pd.DataFrame({'AAA': [4, 5, 6, 7], 'BBB': [10, 20, 30, 40], 'CCC': [100, 50, -30, -50]})

In [ ]:
df.loc[df.AAA >= 5, 'BBB'] = -1
df

AAA  BBB  CCC
0    4   10  100
1    5   -1   50
2    6   -1  -30
3    7   -1  -50

In [ ]:
df.loc[df.AAA >= 5, ['BBB', 'CCC']] = 555
df

AAA  BBB  CCC
0    4   10  100
1    5  555  555
2    6  555  555
3    7  555  555

In [ ]:
df_mask = pd.DataFrame({'AAA': [True] * 4, 'BBB': [False] * 4, 'CCC': [True, False] * 2})
df_mask

AAA    BBB    CCC
0  True  False   True
1  True  False  False
2  True  False   True
3  True  False  False

In [ ]:
df.where(df_mask, -1000)

AAA   BBB   CCC
0    4 -1000   100
1    5 -1000 -1000
2    6 -1000   555
3    7 -1000 -1000

In [ ]:
 df['logic'] = np.where(df['AAA'] > 5, 'high', 'low')
 df

AAA  BBB  CCC logic
0    4   10  100   low
1    5  555  555   low
2    6  555  555  high
3    7  555  555  high

In [ ]:
df.loc[(df['AAA'] < 6) & (df['CCC'] >= -40), 'AAA']

0    4
1    5
Name: AAA, dtype: int64

In [ ]:
df.loc[(df['AAA'] < 6) | (df['CCC'] >= -40), 'AAA']

0    4
1    5
2    6
3    7
Name: AAA, dtype: int64

In [ ]:
df[(df.AAA <= 6) & (df.index.isin([0, 2, 4]))]

AAA  BBB  CCC logic
0    4   10  100   low
2    6  555  555  high

In [ ]:
new_cols = [str(x) + "_cat" for x in df.columns]
new_cols

['AAA_cat', 'BBB_cat', 'CCC_cat', 'logic_cat']